In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

In [2]:
cleaned_orders = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_orders.csv")
cleaned_order_items = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_order_items.csv")
cleaned_order_payments = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_order_payments.csv")
cleaned_order_reviews = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_order_reviews.csv")
cleaned_customers = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_customers.csv")
cleaned_products = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_products.csv")
cleaned_sellers = pd.read_csv(PROCESSED_DATA_DIR / "cleaned_sellers.csv")

cleaned_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_purchase_year,order_purchase_month,order_purchase_year_month,delivery_days,estimated_delivery_days,delivery_delay_days,is_late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017-10-02,2017,10,2017-10,8.0,15,-8.0,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018-07-24,2018,7,2018-07,13.0,19,-6.0,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018-08-08,2018,8,2018-08,9.0,26,-18.0,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017-11-18,2017,11,2017-11,13.0,26,-13.0,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018-02-13,2018,2,2018-02,2.0,12,-10.0,False

In [3]:
cleaned_tables = {
    "cleaned_orders": cleaned_orders,
    "cleaned_order_items": cleaned_order_items,
    "cleaned_order_payments": cleaned_order_payments,
    "cleaned_order_reviews": cleaned_order_reviews,
    "cleaned_customers": cleaned_customers,
    "cleaned_products": cleaned_products,
    "cleaned_sellers": cleaned_sellers,
}

summary = []

for table_name, df in cleaned_tables.items():
    summary.append(
        {
            "table_name": table_name,
            "row_count": df.shape[0],
            "column_count": df.shape[1],
            "duplicate_rows": df.duplicated().sum(),
        }
    )

pd.DataFrame(summary)

               table_name  row_count  column_count  duplicate_rows
0          cleaned_orders      99441            16               0
1     cleaned_order_items     112650             8               0
2  cleaned_order_payments     103886             5               0
3   cleaned_order_reviews      99224             8               0
4       cleaned_customers      99441             5               0
5        cleaned_products      32951            10               0
6         cleaned_sellers       3095             4               0

In [4]:
cleaned_orders[
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_purchase_year",
        "order_purchase_month",
        "order_purchase_year_month",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days",
        "is_late_delivery",
    ]
].head()

,order_id,order_status,order_purchase_timestamp,order_purchase_year,order_purchase_month,order_purchase_year_month,delivery_days,estimated_delivery_days,delivery_delay_days,is_late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,2017,10,2017-10,8.0,15,-8.0,False
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,2018,7,2018-07,13.0,19,-6.0,False
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,2018,8,2018-08,9.0,26,-18.0,False
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,2017,11,2017-11,13.0,26,-13.0,False
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,2018,2,2018-02,2.0,12,-10.0,False

In [5]:
cleaned_order_items[
    [
        "order_id",
        "order_item_id",
        "product_id",
        "seller_id",
        "price",
        "freight_value",
        "total_item_value",
    ]
].head()

,order_id,order_item_id,product_id,seller_id,price,freight_value,total_item_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,218.04

In [6]:
cleaned_products[
    [
        "product_id",
        "product_category_name",
        "product_category_name_english",
    ]
].head(20)

,product_id,product_category_name,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,musical_instruments
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,cool_stuff
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,furniture_decor
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,home_appliances
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,toys
10,14aa47b7fe5c25522b47b4b29c98dcb9,cama_mesa_banho,bed_bath_table
11,03b63c5fc16691530586ae020c345514,bebes,baby
12,cf55509ea8edaaac1d28fdb16e48fc22,instrumentos_musicais,musical_instruments
13,7bb6f29c2be57716194f96496660c7c2,moveis_decoracao,furniture_decor
14,eb31436580a610f202c859463d8c7415,construcao_ferramentas_seguranca,construction_tools_safety
15,3bb7f144022e6732727d8d838a7b13b3,esporte_lazer,sports_leisure
16,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,perfumery
17,a1b71017a84f92fd8da4aeefba108a24,informatica_acessorios,computers_accessories
18,a0736b92e52f6cead290e30b578413b6,moveis_decoracao,furniture_decor
19,f53103a77d9cf245e579ea37e5ec51f0,cama_mesa_banho,bed_bath_table