In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

POWERBI_DATA_DIR = PROJECT_ROOT / "outputs" / "powerbi_data"

fact_sales = pd.read_csv(POWERBI_DATA_DIR / "fact_sales.csv")
dim_date = pd.read_csv(POWERBI_DATA_DIR / "dim_date.csv")
dim_products = pd.read_csv(POWERBI_DATA_DIR / "dim_products.csv")
dim_customers = pd.read_csv(POWERBI_DATA_DIR / "dim_customers.csv")
dim_sellers = pd.read_csv(POWERBI_DATA_DIR / "dim_sellers.csv")

In [2]:
tables = {
    "fact_sales": fact_sales,
    "dim_date": dim_date,
    "dim_products": dim_products,
    "dim_customers": dim_customers,
    "dim_sellers": dim_sellers,
}

summary = []

for table_name, df in tables.items():
    summary.append(
        {
            "table_name": table_name,
            "row_count": df.shape[0],
            "column_count": df.shape[1],
            "duplicate_rows": df.duplicated().sum(),
        }
    )

pd.DataFrame(summary)

      table_name  row_count  column_count  duplicate_rows
0     fact_sales     110197            21               0
1       dim_date        634             6               0
2   dim_products      32951            10               0
3  dim_customers      99441             5               0
4    dim_sellers       3095             4               0

In [3]:
fact_sales.head()

,order_id,order_item_id,customer_id,product_id,seller_id,order_date,order_purchase_year,order_purchase_month,order_purchase_year_month,product_revenue,...,total_item_value,delivery_days,estimated_delivery_days,delivery_delay_days,is_late_delivery,payment_types,total_payment_value,average_installments,average_review_score,has_review_comment
0,e481f51cbdc54678b7cc49136f2d6af7,1,9ef432eb6251297304e76186b10a928d,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-02,2017,10,2017-10,29.99,...,38.71,8.0,15,-8.0,0,"credit_card,voucher",38.71,1.0,4.0,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,1,b0830fb4747a6c6d20dea0b8c802d7ef,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-24,2018,7,2018-07,118.70,...,141.46,13.0,19,-6.0,0,boleto,141.46,1.0,4.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,1,41ce2a54c0b03bf3443c3d931a367089,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-08,2018,8,2018-08,159.90,...,179.12,9.0,26,-18.0,0,credit_card,179.12,3.0,5.0,0.0
3,949d5b44dbf5de918fe9c16f97b45f8a,1,f88197465ea7920adcdbec7375364d82,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-18,2017,11,2017-11,45.00,...,72.20,13.0,26,-13.0,0,credit_card,72.20,1.0,5.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,1,8ab97904e6daea8866dbdbc4fb7aad2c,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-13,2018,2,2018-02,19.90,...,28.62,2.0,12,-10.0,0,credit_card,28.62,1.0,5.0,0.0

In [4]:
fact_sales[["product_revenue", "freight_value", "total_item_value"]].sum()

product_revenue     13221498.11
freight_value        2198275.64
total_item_value    15419773.75
dtype: float64